# Generated by Django 4.2.30 on 2026-04-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_no', models.IntegerField()),
                ('apartment_name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_type', models.CharField(choices=[('rent', 'Rent'), ('service_charge', 'Service Charge'), ('water_bill', 'Water Bill'), ('gas_bill', 'Gas Bill'), ('electricity_bill', 'Electricity Bill')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='core.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('total_apartment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nid', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('profile_pic_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='PaidBill',
            fields=[
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paid', serialize=False, to='core.billing')),
                ('date_paid', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingBill',
            fields=[
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pending', serialize=False, to='core.billing')),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingComplaint',
            fields=[
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pending', serialize=False, to='core.complaint')),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resident', serialize=False, to='core.person')),
                ('resident_type', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant')], default='tenant', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.building'),
        ),
        migrations.CreateModel(
            name='SolvedComplaint',
            fields=[
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solved', serialize=False, to='core.complaint')),
                ('date_solved', models.DateField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_complaints', to='core.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.building')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='core.manager')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='core.resident'),
        ),
        migrations.AddField(
            model_name='building',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='core.manager'),
        ),
        migrations.AddField(
            model_name='billing',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to='core.manager'),
        ),
        migrations.AddField(
            model_name='billing',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='core.resident'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='core.resident'),
        ),
    ]
